import { readFile, writeFile } from "node:fs/promises";
import { fileURLToPath } from "node:url";
import path from "node:path";

const projectRoot = path.resolve(path.dirname(fileURLToPath(import.meta.url)), "..");
const sources = [
  "src/styles/base.css",
  "src/styles/components.css",
  "src/themes/obsidian.css",
  "src/themes/pixel-sky.css"
];

const parts = await Promise.all(sources.map(async (source) => {
  const content = await readFile(path.join(projectRoot, source), "utf8");
  return `/* source: ${source} */\n${content.trim()}\n`;
}));

const output = `${[
  "/* Generated by tools/build-styles.mjs. Edit files under src/styles and src/themes. */",
  ...parts
].join("\n")}\n`;

const outputPath = path.join(projectRoot, "styles.css");
const currentOutput = await readFile(outputPath, "utf8").catch(() => "");
if (currentOutput !== output) {
  await writeFile(outputPath, output, "utf8");
  console.log(`Built styles.css from ${sources.length} isolated sources.`);
} else {
  console.log(`styles.css is current (${sources.length} isolated sources).`);
}
